### ISSUE TITLE
Failed to load and save snapshots

### ISSUE THREAD

**Issue by wyatt-wong** [samkusin/clemens_iigs#106] opened 2023-04-08 20:36 UTC
I found that sometimes the emulator failed to save and load a snapshot. Morever, I found that it also failed to load a previously imported disk image at all.

Please check if you can recover the snapshot that I attached to you.

[Test.clemens-sav.zip](https://github.com/samkusin/clemens_iigs/files/11184207/Test.clemens-sav.zip)

**Comment by samkusin** [comment] 2023-04-09 17:32
I took a look at this snapshot.   It looks like the save failed before any disks were serialized and not enough information is available to restore it.   This type of bug should be able to be detected during the save process instead of during load.

The snapshot you sent does provide enough information to fix this occurrance in the next release.

**Comment by samkusin** [comment] 2023-07-21 06:35
Snapshot de-serialization had issues with memory allocation that resulted in corrupted save files.   The memory management in this area has been refactored in:

PR #111 and regressions were fixed in #113 and #114 .

Snapshots have been stable since then and will close this issue.

**Closed by samkusin** 2023-07-21 06:35 UTC
Labels: 0.6 release
