### ISSUE TITLE
Use single mouse cursor to access the Configuration Panel and the Display Panel

### ISSUE THREAD

**Issue by wyatt-wong** [samkusin/clemens_iigs#104] opened 2023-04-08 18:11 UTC
Currently the emulator require using a mouse cursor to access the configuration panel on the left to interact with the disk drive, reboot, reset, etc. And when the mouse cursor is inside the display panel on the right, the mouse cursor is locked inside the display panel unless user press Ctrl+Option+Command (in macOS) to release the mouse cursor.

I suggest to simplify it and use a single mouse cursor to access both the configuration panel on the left and the display panel on the right. Other emulators such as AppleWin and Virtual ][ are using a single mouse cursor to access all the functions without user to press a specific key combination to release the mouse cursor from display panel.

**Comment by samkusin** [comment] 2023-04-08 18:50
Possible duplicate of #87.

**Comment by samkusin** [comment] 2023-05-14 06:07
Duplicate of #87

**Closed by samkusin** 2023-05-14 06:07 UTC
